global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nomad
    consul_sd_configs:
      - server: localhost:8500
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,http,.*
        action: keep

  - job_name: consul
    static_configs:
      - targets: ["localhost:8500"]
    metrics_path: /v1/agent/metrics
    params:
      format: [prometheus]

  - job_name: iptables-exporter
    consul_sd_configs:
      - server: localhost:8500
        services: [iptables-exporter]

rule_files:
  - /etc/prometheus/alerts/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]
